FROM solr:7.2.1
#VOLUME /opt/solr/server/solr/mycores
RUN wget https://github.com/lucidworks/banana/archive/v1.6.19.zip && unzip v1.6.19.zip && mv banana-1.6.19/src server/solr-webapp/webapp/banana && rm v1.6.19.zip